# Generated by Django 4.2.10 on 2026-04-12 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('workshop_video', models.FileField(blank=True, help_text='Vidéo de fabrication — 30 secondes max', null=True, upload_to='producer_videos/')),
                ('workshop_photo', models.ImageField(blank=True, null=True, upload_to='producer_photos/')),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('speciality', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
