# Generated by Django 4.2.10 on 2026-03-27 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproducer',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_producers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentproducer',
            name='producer',
            field=models.ForeignKey(limit_choices_to={'role': 'producer'}, on_delete=django.db.models.deletion.CASCADE, related_name='managing_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='agentproducer',
            unique_together={('agent', 'producer')},
        ),
    ]
