# Generated by Django 4.2.10 on 2026-05-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cities', models.TextField(help_text='Villes couvertes, séparées par des virgules')),
                ('fee', models.DecimalField(decimal_places=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['fee'],
            },
        ),
    ]
