# Generated by Django 4.2.10 on 2026-05-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_deliveryzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_abandoned_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
