--
-- PostgreSQL database dump
--

\restrict gcHlZfAlMSihVQgfHUUQA0KL9S7PLOVw5yJ1omIaNir2Z7s7upnxFVlOCD3BAFN

-- Dumped from database version 14.22 (Ubuntu 14.22-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.22 (Ubuntu 14.22-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agents_agentproducer; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.agents_agentproducer (
    id bigint NOT NULL,
    added_at timestamp with time zone NOT NULL,
    agent_id bigint NOT NULL,
    producer_id bigint NOT NULL
);


ALTER TABLE public.agents_agentproducer OWNER TO sahel;

--
-- Name: agents_agentproducer_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.agents_agentproducer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agents_agentproducer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO sahel;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO sahel;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO sahel;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delivery_deliverytracking; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.delivery_deliverytracking (
    id bigint NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    order_id bigint NOT NULL
);


ALTER TABLE public.delivery_deliverytracking OWNER TO sahel;

--
-- Name: delivery_deliverytracking_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.delivery_deliverytracking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_deliverytracking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO sahel;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO sahel;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO sahel;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO sahel;

--
-- Name: orders_cart; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.orders_cart (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.orders_cart OWNER TO sahel;

--
-- Name: orders_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.orders_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_cartitem; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.orders_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT orders_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.orders_cartitem OWNER TO sahel;

--
-- Name: orders_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.orders_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_order; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.orders_order (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(12,0) NOT NULL,
    delivery_address text NOT NULL,
    delivery_fee numeric(8,0) NOT NULL,
    cinetpay_transaction_id character varying(100) NOT NULL,
    is_delivery_confirmed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.orders_order OWNER TO sahel;

--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.orders_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_orderitem; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.orders_orderitem (
    id bigint NOT NULL,
    product_name character varying(200) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,0) NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint,
    CONSTRAINT orders_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.orders_orderitem OWNER TO sahel;

--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.orders_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_category; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.products_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(50) NOT NULL,
    image character varying(100)
);


ALTER TABLE public.products_category OWNER TO sahel;

--
-- Name: products_category_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.products_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_like; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.products_like (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.products_like OWNER TO sahel;

--
-- Name: products_like_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.products_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.products_product (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    description text NOT NULL,
    price numeric(10,0) NOT NULL,
    stock integer NOT NULL,
    location character varying(200) NOT NULL,
    is_available boolean NOT NULL,
    views_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint,
    producer_id bigint NOT NULL,
    CONSTRAINT products_product_stock_check CHECK ((stock >= 0)),
    CONSTRAINT products_product_views_count_check CHECK ((views_count >= 0))
);


ALTER TABLE public.products_product OWNER TO sahel;

--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.products_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_productimage; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.products_productimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    is_main boolean NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.products_productimage OWNER TO sahel;

--
-- Name: products_productimage_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.products_productimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_productimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_rating; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.products_rating (
    id bigint NOT NULL,
    score integer NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.products_rating OWNER TO sahel;

--
-- Name: products_rating_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.products_rating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_rating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    phone character varying(20) NOT NULL,
    address text NOT NULL,
    avatar character varying(100),
    is_verified boolean NOT NULL,
    whatsapp character varying(20) NOT NULL
);


ALTER TABLE public.users_user OWNER TO sahel;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO sahel;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: sahel
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO sahel;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: sahel
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: agents_agentproducer; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.agents_agentproducer (id, added_at, agent_id, producer_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Utilisateur	6	add_user
22	Can change Utilisateur	6	change_user
23	Can delete Utilisateur	6	delete_user
24	Can view Utilisateur	6	view_user
25	Can add category	7	add_category
26	Can change category	7	change_category
27	Can delete category	7	delete_category
28	Can view category	7	view_category
29	Can add like	8	add_like
30	Can change like	8	change_like
31	Can delete like	8	delete_like
32	Can view like	8	view_like
33	Can add product	9	add_product
34	Can change product	9	change_product
35	Can delete product	9	delete_product
36	Can view product	9	view_product
37	Can add product image	10	add_productimage
38	Can change product image	10	change_productimage
39	Can delete product image	10	delete_productimage
40	Can view product image	10	view_productimage
41	Can add rating	11	add_rating
42	Can change rating	11	change_rating
43	Can delete rating	11	delete_rating
44	Can view rating	11	view_rating
45	Can add cart	12	add_cart
46	Can change cart	12	change_cart
47	Can delete cart	12	delete_cart
48	Can view cart	12	view_cart
49	Can add cart item	13	add_cartitem
50	Can change cart item	13	change_cartitem
51	Can delete cart item	13	delete_cartitem
52	Can view cart item	13	view_cartitem
53	Can add order	14	add_order
54	Can change order	14	change_order
55	Can delete order	14	delete_order
56	Can view order	14	view_order
57	Can add order item	15	add_orderitem
58	Can change order item	15	change_orderitem
59	Can delete order item	15	delete_orderitem
60	Can view order item	15	view_orderitem
61	Can add delivery tracking	16	add_deliverytracking
62	Can change delivery tracking	16	change_deliverytracking
63	Can delete delivery tracking	16	delete_deliverytracking
64	Can view delivery tracking	16	view_deliverytracking
65	Can add agent producer	17	add_agentproducer
66	Can change agent producer	17	change_agentproducer
67	Can delete agent producer	17	delete_agentproducer
68	Can view agent producer	17	view_agentproducer
\.


--
-- Data for Name: delivery_deliverytracking; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.delivery_deliverytracking (id, latitude, longitude, last_updated, order_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-03-27 13:15:17.553436+01	1	Poterie	1	[{"added": {}}]	7	1
2	2026-03-27 13:17:01.118603+01	2	Vannerie	1	[{"added": {}}]	7	1
3	2026-03-27 13:18:39.70325+01	3	Bijouterie	1	[{"added": {}}]	7	1
4	2026-03-27 13:29:20.868528+01	1	Colier Mémoire du Désert	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (1)"}}]	9	1
5	2026-03-27 13:32:42.614516+01	2	Poterie du sahel	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (2)"}}, {"added": {"name": "product image", "object": "ProductImage object (3)"}}, {"added": {"name": "product image", "object": "ProductImage object (4)"}}, {"added": {"name": "product image", "object": "ProductImage object (5)"}}]	9	1
6	2026-03-27 13:35:24.552299+01	3	Panier	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (6)"}}, {"added": {"name": "product image", "object": "ProductImage object (7)"}}]	9	1
7	2026-03-27 13:36:54.306941+01	4	Tissu	1	[{"added": {}}]	7	1
8	2026-03-27 13:38:54.346131+01	4	pagne	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (8)"}}, {"added": {"name": "product image", "object": "ProductImage object (9)"}}]	9	1
9	2026-03-27 13:39:13.43375+01	5	Salon	1	[{"added": {}}]	7	1
10	2026-03-27 13:40:54.795237+01	5	salon traditionnel	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (10)"}}]	9	1
11	2026-03-31 11:03:38.352821+01	6	PotDor	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (11)"}}]	9	1
12	2026-03-31 11:37:27.267584+01	6	Sac	1	[{"added": {}}]	7	1
13	2026-03-31 11:39:11.118917+01	7	La banane	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (12)"}}, {"added": {"name": "product image", "object": "ProductImage object (13)"}}, {"added": {"name": "product image", "object": "ProductImage object (14)"}}, {"added": {"name": "product image", "object": "ProductImage object (15)"}}, {"added": {"name": "product image", "object": "ProductImage object (16)"}}]	9	1
14	2026-03-31 12:17:16.483249+01	8	SacAMain	1	[{"added": {}}]	9	1
15	2026-03-31 12:19:26.056953+01	8	SacAMain	2	[{"added": {"name": "product image", "object": "ProductImage object (17)"}}]	9	1
16	2026-04-06 10:14:38.058409+01	7	ModelHabit	1	[{"added": {}}]	7	1
17	2026-04-06 10:19:08.122177+01	9	Ayla Men	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (18)"}}]	9	1
18	2026-04-06 10:21:58.91918+01	10	Émeraude Roya	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (19)"}}]	9	1
19	2026-04-06 10:23:59.586511+01	11	Noir & Sable Prestige	1	[{"added": {}}]	9	1
20	2026-04-06 10:26:24.377573+01	12	Blanc Cassé & Ligne Noire	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (20)"}}, {"added": {"name": "product image", "object": "ProductImage object (21)"}}]	9	1
21	2026-04-06 10:28:42.225219+01	13	Édition Royal Ikat	1	[{"added": {}}]	9	1
22	2026-04-06 10:29:19.185332+01	7	ModelHabitHomme	2	[{"changed": {"fields": ["Name"]}}]	7	1
23	2026-04-06 10:29:52.244989+01	8	ModelHabitFemme	1	[{"added": {}}]	7	1
24	2026-04-06 10:31:29.370066+01	14	Néa Coton Ikat	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (22)"}}]	9	1
25	2026-04-06 10:33:28.06493+01	15	Éclat Signature	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (23)"}}, {"added": {"name": "product image", "object": "ProductImage object (24)"}}]	9	1
26	2026-04-06 10:35:23.425932+01	16	Ornina Royale	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (25)"}}, {"added": {"name": "product image", "object": "ProductImage object (26)"}}, {"added": {"name": "product image", "object": "ProductImage object (27)"}}]	9	1
27	2026-04-06 10:37:17.411189+01	17	Nahla Indigo Chic	1	[{"added": {}}]	9	1
28	2026-04-06 10:38:24.357475+01	17	Nahla Indigo Chic	2	[{"added": {"name": "product image", "object": "ProductImage object (28)"}}]	9	1
29	2026-04-06 10:41:01.629315+01	13	Édition Royal Ikat	2	[{"added": {"name": "product image", "object": "ProductImage object (29)"}}, {"added": {"name": "product image", "object": "ProductImage object (30)"}}, {"added": {"name": "product image", "object": "ProductImage object (31)"}}]	9	1
30	2026-04-06 10:42:07.833523+01	11	Noir & Sable Prestige	2	[{"added": {"name": "product image", "object": "ProductImage object (32)"}}]	9	1
31	2026-04-06 10:52:14.076131+01	9	Babouche	1	[{"added": {}}]	7	1
32	2026-04-06 10:54:12.101272+01	18	sandale	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (33)"}}]	9	1
33	2026-04-06 10:56:31.601994+01	19	Choschos	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (34)"}}]	9	1
34	2026-04-06 11:00:26.661204+01	20	b2cg	1	[{"added": {}}]	9	1
35	2026-04-06 11:02:13.163058+01	21	Sandlux	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (35)"}}]	9	1
36	2026-04-06 11:02:49.598386+01	6	PotDor	3		9	1
37	2026-04-06 11:03:37.199491+01	20	b2cg	2	[{"added": {"name": "product image", "object": "ProductImage object (36)"}}]	9	1
38	2026-04-06 11:06:09.328628+01	10	Bracelet	1	[{"added": {}}]	7	1
39	2026-04-06 11:07:18.185716+01	22	ColiBr	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (37)"}}]	9	1
40	2026-04-06 11:08:42.746956+01	23	Bacbridge	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (38)"}}]	9	1
41	2026-04-06 11:09:37.504744+01	24	bpts	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (39)"}}]	9	1
42	2026-04-06 11:10:23.310908+01	25	b2b2	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (40)"}}]	9	1
43	2026-04-06 11:11:28.90012+01	11	Colier	1	[{"added": {}}]	7	1
44	2026-04-06 11:16:45.801247+01	26	Ambre du Tibet	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (41)"}}]	9	1
45	2026-04-06 11:19:05.068793+01	27	Collier Pendentif	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (42)"}}]	9	1
46	2026-04-06 11:21:05.427623+01	28	Collier Afro-Rasta en cauris et perles multicolores	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (43)"}}]	9	1
47	2026-04-06 11:26:09.197413+01	29	Soleil de Maroua	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (44)"}}]	9	1
48	2026-04-06 11:28:54.461755+01	30	sac djembé	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (45)"}}]	9	1
49	2026-04-06 11:31:34.655374+01	31	Harmattan	1	[{"added": {}}, {"added": {"name": "product image", "object": "ProductImage object (46)"}}]	9	1
50	2026-04-06 11:34:13.531266+01	32	TÉNÉRÉ	1	[{"added": {}}]	9	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	users	user
7	products	category
8	products	like
9	products	product
10	products	productimage
11	products	rating
12	orders	cart
13	orders	cartitem
14	orders	order
15	orders	orderitem
16	delivery	deliverytracking
17	agents	agentproducer
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-03-27 11:09:38.193775+01
2	contenttypes	0002_remove_content_type_name	2026-03-27 11:09:38.202451+01
3	auth	0001_initial	2026-03-27 11:09:38.252405+01
4	auth	0002_alter_permission_name_max_length	2026-03-27 11:09:38.259442+01
5	auth	0003_alter_user_email_max_length	2026-03-27 11:09:38.267369+01
6	auth	0004_alter_user_username_opts	2026-03-27 11:09:38.273689+01
7	auth	0005_alter_user_last_login_null	2026-03-27 11:09:38.281025+01
8	auth	0006_require_contenttypes_0002	2026-03-27 11:09:38.283663+01
9	auth	0007_alter_validators_add_error_messages	2026-03-27 11:09:38.290937+01
10	auth	0008_alter_user_username_max_length	2026-03-27 11:09:38.297998+01
11	auth	0009_alter_user_last_name_max_length	2026-03-27 11:09:38.304038+01
12	auth	0010_alter_group_name_max_length	2026-03-27 11:09:38.312291+01
13	auth	0011_update_proxy_permissions	2026-03-27 11:09:38.318719+01
14	auth	0012_alter_user_first_name_max_length	2026-03-27 11:09:38.326891+01
15	users	0001_initial	2026-03-27 11:09:38.38026+01
16	admin	0001_initial	2026-03-27 11:09:38.405722+01
17	admin	0002_logentry_remove_auto_add	2026-03-27 11:09:38.415805+01
18	admin	0003_logentry_add_action_flag_choices	2026-03-27 11:09:38.424308+01
19	agents	0001_initial	2026-03-27 11:09:38.432656+01
20	agents	0002_initial	2026-03-27 11:09:38.469333+01
21	orders	0001_initial	2026-03-27 11:09:38.501531+01
22	delivery	0001_initial	2026-03-27 11:09:38.512698+01
23	delivery	0002_initial	2026-03-27 11:09:38.522408+01
24	products	0001_initial	2026-03-27 11:09:38.5665+01
25	orders	0002_initial	2026-03-27 11:09:38.579175+01
26	orders	0003_initial	2026-03-27 11:09:38.630286+01
27	products	0002_initial	2026-03-27 11:09:38.760756+01
28	sessions	0001_initial	2026-03-27 11:09:38.778293+01
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
9rowlvhqynpj2y4khnujxn9uilmua31k	.eJxVjDsOwjAQBe_iGll2_KekzxmstXeNA8iR4qRC3J1ESgHtm5n3ZhG2tcat0xInZFcm2eV3S5Cf1A6AD2j3mee5rcuU-KHwk3Y-zkiv2-n-HVToda-Jch6wIPhQisrKkIFggyMnlJaQ3M6MlgKLJa-tKg4zKqLB-iCUI_b5AhzQOOA:1w64S1:ywrWg5YXXdWABc14VvgmGDUs-z9p-YJq1BhDxz6qUMQ	2026-04-10 11:30:01.070266+01
z6z7a1rz1xml1z8dy0y5hc55phv3qlkh	.eJxVjDsOwjAQBe_iGll2_KekzxmstXeNA8iR4qRC3J1ESgHtm5n3ZhG2tcat0xInZFcm2eV3S5Cf1A6AD2j3mee5rcuU-KHwk3Y-zkiv2-n-HVToda-Jch6wIPhQisrKkIFggyMnlJaQ3M6MlgKLJa-tKg4zKqLB-iCUI_b5AhzQOOA:1w7VDC:VUHHvIBvRFJUyY0le9nMkKZUyCCK1nh-MmJAasN_bd0	2026-04-14 10:16:38.998234+01
\.


--
-- Data for Name: orders_cart; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.orders_cart (id, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: orders_cartitem; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.orders_cartitem (id, quantity, cart_id, product_id) FROM stdin;
\.


--
-- Data for Name: orders_order; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.orders_order (id, status, total_amount, delivery_address, delivery_fee, cinetpay_transaction_id, is_delivery_confirmed, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: orders_orderitem; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.orders_orderitem (id, product_name, quantity, unit_price, order_id, product_id) FROM stdin;
\.


--
-- Data for Name: products_category; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.products_category (id, name, slug, image) FROM stdin;
1	Poterie	poterie	categories/poterie7.jpeg
2	Vannerie	vannerie	categories/vanerie.jpeg
3	Bijouterie	bijouterie	categories/collier1.jpeg
4	Tissu	tissu	categories/tissu1.jpeg
5	Salon	salon	categories/salon.jpeg
6	Sac	sac	categories/sac5.jpeg
7	ModelHabitHomme	modelhabit	categories/th7.jpg
8	ModelHabitFemme	MHF	categories/t4.jpg
9	Babouche	babouche	categories/babouches_7.jpeg
10	Bracelet	bracelet	categories/bracelets4.jpeg
11	Colier	colier	categories/collier_4.jpeg
\.


--
-- Data for Name: products_like; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.products_like (id, created_at, product_id, user_id) FROM stdin;
2	2026-03-31 10:14:55.461253+01	5	1
3	2026-04-06 01:56:52.302022+01	2	6
\.


--
-- Data for Name: products_product; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.products_product (id, name, description, price, stock, location, is_available, views_count, created_at, updated_at, category_id, producer_id) FROM stdin;
1	Colier Mémoire du Désert	Un pendentif en argent martelé où une goutte d'ambre capte la lumière comme un petit soleil, ses gravures rappelant les courbes des dunes et les chemins partagés. Portez ce bijou comme un talisman : il raconte en silence un voyage, un souvenir et la promesse d'un nouveau départ.	5000	50	Mora	t	5	2026-03-27 13:29:20.865152+01	2026-03-27 13:29:20.865166+01	3	3
4	pagne	une jarre faite main en terre cuite rouge, ornée de motifs géométriques gravés qui reprennent les rythmes du vent et les signes des anciens gardiens du désert. Témoin des gestes transmis de génération en génération, elle garde la mémoire des foyers du Sahel et apporte à votre intérieur chaleur, histoire et authenticité.	15000	150	Kaele	t	10	2026-03-27 13:38:54.337287+01	2026-03-27 13:38:54.337302+01	4	3
18	sandale	Sandale somple avec des motifs doux	1600	60		t	0	2026-04-06 10:54:12.098826+01	2026-04-06 10:54:12.098846+01	9	4
7	La banane	Sac de sortie rapide	2500	24		t	6	2026-03-31 11:39:11.112994+01	2026-03-31 11:39:11.113013+01	6	2
19	Choschos	Babouche maison femme	1500	20		t	0	2026-04-06 10:56:31.594646+01	2026-04-06 10:56:31.594689+01	9	4
5	salon traditionnel	un ensemble mobilier confectionné localement, mêlant bois sculpté, cuir tanné et textiles tissés à la main, où les motifs et finitions reflètent les récits et symboles des communautés du Sahel. Pensé pour accueillir, partager et durer, il transforme l’espace en lieu de mémoire et de convivialité, alliant confort authentique et savoir‑faire transmis de génération en génération.	500000	15	Maroua	t	8	2026-03-27 13:40:54.792445+01	2026-03-27 13:40:54.792458+01	5	3
8	SacAMain	C'est un sac fabriquer par une jeune fille qui a perdu sa maman et s'est lance dans la production de ce genre de sac pour pouvoir tenir le coup	1500	20	Makabai	t	5	2026-03-31 12:17:16.479382+01	2026-03-31 12:19:26.052141+01	6	3
17	Nahla Indigo Chic	Kaftan ample à motifs graphiques, finitions décoratives et tombé élégant. Un style à la fois traditionnel et moderne, idéal pour marquer les grandes occasions avec élégance.	19000	21		t	2	2026-04-06 10:37:17.409311+01	2026-04-06 10:38:24.353999+01	8	3
3	Panier	une jarre faite main en terre cuite rouge, ornée de motifs géométriques gravés qui reprennent les rythmes du vent et les signes des anciens gardiens du désert. Témoin des gestes transmis de génération en génération, elle garde la mémoire des foyers du Sahel et apporte à votre intérieur chaleur, histoire et authenticité.	2000	65		t	4	2026-03-27 13:35:24.548894+01	2026-03-27 13:35:24.548907+01	2	4
28	Collier Afro-Rasta en cauris et perles multicolores	Collier artisanal d'inspiration africaine et rastafari, composé de coquillages cauris naturels espacés régulièrement le long d'un cordon noir. Entre chaque cauri, des perles en bois et en résine aux couleurs vives — rouge, jaune, vert et noir — rappellent les teintes panafricaines et le mouvement rasta. Des perles cylindriques noires viennent rythmer l'ensemble et apporter du contraste. Ce bijou unisexe, à la fois ethnique et bohème, se porte aussi bien en sautoir qu'en collier mi-long. Idéal pour affirmer un style roots, festival ou afro-chic.	12000	50		t	0	2026-04-06 11:21:05.416246+01	2026-04-06 11:21:05.416295+01	11	3
2	Poterie du sahel	une jarre faite main en terre cuite rouge, ornée de motifs géométriques gravés qui reprennent les rythmes du vent et les signes des anciens gardiens du désert. Témoin des gestes transmis de génération en génération, elle garde la mémoire des foyers du Sahel et apporte à votre intérieur chaleur, histoire et authenticité.	12000	100		t	6	2026-03-27 13:32:42.605701+01	2026-03-27 13:32:42.605714+01	1	2
10	Émeraude Roya	Un ensemble chic vert émeraude à la coupe moderne, avec une patte asymétrique et des détails dorés. Élégant, sobre et confortable pour une allure haut de gamme.	20000	25		t	0	2026-04-06 10:21:58.913918+01	2026-04-06 10:21:58.913933+01	7	3
21	Sandlux	sandale de sortie comfortable pour les femmes	5000	15		t	0	2026-04-06 11:02:13.160267+01	2026-04-06 11:02:13.16028+01	9	4
12	Blanc Cassé & Ligne Noire	Costume blanc cassé à la ligne noire contrastante, style moderne et très classe. Coupe ajustée, allure propre et parfaite pour un look chic et distingué.	21000	15		t	0	2026-04-06 10:26:24.372635+01	2026-04-06 10:26:24.372647+01	7	4
11	Noir & Sable Prestige	Un ensemble élégant gris clair avec un col/pli contrasté noir et des finitions minimalistes. Coupe moderne, allure soignée et style intemporel pour toutes occasions.	14000	100		t	0	2026-04-06 10:23:59.585406+01	2026-04-06 10:42:07.827549+01	7	3
14	Néa Coton Ikat	Robe légère au design audacieux, finitions soignées et motifs contrastés. Parfaite pour un style frais, chic et original au quotidien comme en sortie.	7000	24		t	0	2026-04-06 10:31:29.366865+01	2026-04-06 10:31:29.366884+01	8	3
15	Éclat Signature	Ensemble chic au tombé net et à la brillance élégante. La coupe structurée, les manches bouffantes et l’ensemble de détails mettent en valeur un style unique, parfait pour les cérémonies et sorties habillées.	15000	15		t	0	2026-04-06 10:33:28.058373+01	2026-04-06 10:33:28.058386+01	8	4
16	Ornina Royale	Robe stylée à la coupe cintrée, motifs riches et finitions soignées. Une tenue élégante et originale, parfaite pour faire ressortir votre beauté avec classe.	11000	40		t	0	2026-04-06 10:35:23.417886+01	2026-04-06 10:35:23.417926+01	8	2
9	Ayla Men	Ce boubou moderne au bordeaux profond est taillé pour le style et le confort, avec ses détails dorés qui rappellent la chaleur des marchés et la présence du soleil nord-camerounais	15000	45		t	1	2026-04-06 10:19:08.115225+01	2026-04-06 10:19:08.115248+01	7	3
13	Édition Royal Ikat	Boubou premium à l’allure royale : col montant, coupe impeccable et motifs graphiques raffinés. Un style chic, net et distingué pour marquer les grandes occasions.	27000	10		t	1	2026-04-06 10:28:42.222528+01	2026-04-06 10:41:01.624324+01	7	2
20	b2cg	A porter pour cuisiner	4400	18		t	1	2026-04-06 11:00:26.6565+01	2026-04-06 11:03:37.196306+01	9	4
22	ColiBr	Brancelet maison simple	500	1000		t	0	2026-04-06 11:07:18.181709+01	2026-04-06 11:07:18.181733+01	10	6
24	bpts	Bracelet pour tous	400	7000		t	0	2026-04-06 11:09:37.499886+01	2026-04-06 11:09:37.499909+01	10	6
25	b2b2	Bracelet enfant	250	100		t	0	2026-04-06 11:10:23.302519+01	2026-04-06 11:10:23.302562+01	10	6
23	Bacbridge	Un artefact unique qui communique avec le passe	2500	70		t	1	2026-04-06 11:08:42.740002+01	2026-04-06 11:08:42.740055+01	10	6
26	Ambre du Tibet	Ce collier statement est un véritable voyage artisanal. Il se compose de perles généreuses en résine ambrée, turquoise, corail rouge et perles Dzi noir et blanc aux motifs traditionnels, le tout rehaussé d'intercalaires en métal argenté vieilli.\r\n\r\nSon pendentif central en forme de losange, serti dans une monture en argent tibétain finement ciselé, attire immédiatement le regard et apporte une touche de caractère à n'importe quelle tenue.	28000	20		t	0	2026-04-06 11:16:45.796167+01	2026-04-06 11:16:45.796191+01	11	3
27	Collier Pendentif	Plongez dans l'art ancestral africain avec ce magnifique collier à pendentif sculpté à la main. Chaque pièce est unique, taillée dans du bois et de l'os naturel, représentant des masques tribaux, des croix et des figures totémiques aux détails saisissants.	13000	10		t	0	2026-04-06 11:19:05.06476+01	2026-04-06 11:19:05.064785+01	11	3
29	Soleil de Maroua	Sac cabas élégant en toile de jute naturelle, rehaussé d'un imprimé wax africain aux motifs bogolan dans des tons noir, jaune doré et blanc. Son design bicolore allie l'authenticité du tissu africain à la sobriété du lin beige, pour un look à la fois ethnique et raffiné.	7000	17		t	0	2026-04-06 11:26:09.191199+01	2026-04-06 11:26:09.191235+01	6	2
30	sac djembé	C'est un sac à bandoulière artisanal d'Afrique de l'Ouest, probablement originaire du Sahel	6000	15		t	0	2026-04-06 11:28:54.45675+01	2026-04-06 11:28:54.456769+01	6	4
31	Harmattan	nspiré des terres dorées du Sahel, l'ensemble Harmattan capture l'essence des horizons infinis où le sable rencontre le soleil couchant. Tissé à la main dans des tons ocre et safran, ce cabas mêle les rayures multicolores des étoffes sahéliennes à un médaillon de perles artisanales — écho des ornements traditionnels touaregs et peuls.	16000	45		t	0	2026-04-06 11:31:34.652728+01	2026-04-06 11:31:34.652742+01	6	2
32	TÉNÉRÉ	Inspiré des terres ocre et des vents chauds du Sahel, le sac Ténéré marie le cuir grainé couleur sable aux imprimés botaniques rappelant les feuillages des acacias et des palmiers doum qui bordent les oasis sahéliennes.	13500	25		t	0	2026-04-06 11:34:13.527134+01	2026-04-06 11:34:13.52719+01	6	3
\.


--
-- Data for Name: products_productimage; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.products_productimage (id, image, is_main, product_id) FROM stdin;
1	products/collier.jpeg	f	1
2	products/poterie3.jpeg	f	2
3	products/poterie1.jpeg	f	2
4	products/poterie8.jpeg	f	2
5	products/poterie7.jpeg	f	2
6	products/vanerie5.jpeg	f	3
7	products/vanerie3.jpeg	f	3
8	products/tissu1.jpeg	f	4
9	products/tissu2.jpeg	f	4
10	products/salon.jpeg	f	5
12	products/sac5.jpeg	f	7
13	products/sac4.jpeg	f	7
14	products/sac3.jpeg	f	7
15	products/sac1.jpg	f	7
16	products/sac2.jpeg	f	7
17	products/sac1_027HTn5.jpg	f	8
18	products/th5.jpg	f	9
19	products/th4.jpg	f	10
20	products/th2.jpg	f	12
21	products/t2.jpg	f	12
22	products/t1.jpg	f	14
23	products/t6.jpg	f	15
24	products/t5.jpg	f	15
25	products/t11.jpg	f	16
26	products/t10.jpg	f	16
27	products/t9.jpg	f	16
28	products/t3.jpg	f	17
29	products/th___1.jpg	f	13
30	products/th__1.jpg	f	13
31	products/th1.jpg	f	13
32	products/th3.jpg	f	11
33	products/babouches1.jpeg	f	18
34	products/babouches_7.jpeg	f	19
35	products/babouches_2.jpeg	f	21
36	products/babouches_4.jpeg	f	20
37	products/bracelets6.jpeg	f	22
38	products/bracelets4.jpeg	f	23
39	products/bracelets3.jpeg	f	24
40	products/bracelets1.jpeg	f	25
41	products/collier_4.jpeg	f	26
42	products/collier_3.jpeg	f	27
43	products/collier_2.jpeg	f	28
44	products/sac7.jpg	f	29
45	products/sac2_AIcnNB4.jpeg	f	30
46	products/sac3.jpg	f	31
\.


--
-- Data for Name: products_rating; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.products_rating (id, score, comment, created_at, product_id, user_id) FROM stdin;
1	2		2026-03-31 10:15:00.835242+01	4	1
2	3		2026-03-31 10:31:04.865075+01	3	1
3	4		2026-03-31 10:52:38.574658+01	5	1
4	1		2026-03-31 11:39:35.965257+01	7	1
5	2		2026-03-31 12:14:18.892164+01	2	1
6	4		2026-04-02 12:24:05.291127+01	1	6
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, phone, address, avatar, is_verified, whatsapp) FROM stdin;
2	pbkdf2_sha256$600000$RtUcWfdWipAaOtXW7aMXQx$099fhyNRP8nVgqm3YmGMc3twqnKvoSEax5SFL/AtqkI=	\N	f	IHONGUI			ihongui@gmail.com	f	t	2026-03-27 13:21:12.872653+01	producer	652584888			f	
3	pbkdf2_sha256$600000$KHbCeRubYeP1ebNil4xRvi$FQ6mR89Aoqbmzssdn1/l9PyGTJndfkzhWTue7/gD2PE=	\N	f	KEMTSOP			kemtsop@gmail.com	f	t	2026-03-27 13:23:49.48625+01	producer	6425897554			f	
4	pbkdf2_sha256$600000$pcuqWiDovh9dhvIViKKuo2$WZr7CGXASHSoXFGiFi9KOQkDSg9LqKNj7/+hieFkJek=	\N	f	TAFFO			taffo@gmail.com	f	t	2026-03-27 13:24:57.622998+01	producer	655889441			f	
1	pbkdf2_sha256$600000$VOTI6GkmrRS89lxtDR4y2U$5fo98LlzxvsP9IIRXqLvEn+qxMqe50yhWGNO1gl89I4=	2026-03-31 10:16:38.993604+01	t	joel			kemtsopjoel85@gmail.com	t	t	2026-03-27 11:21:17.37895+01	client				f	
5	pbkdf2_sha256$600000$redBiMT6IPFdDiG4S2QqII$EOL+GYPrR5cREMfLnfvHPrupF6GnM7+uQ0HpqFF5i3M=	\N	f	john			john@gmail.com	f	t	2026-03-31 12:58:52.695223+01	client	6425497554			f	
6	pbkdf2_sha256$600000$x2v6yv91Tl6PSruX1LaIAw$iFS506s5shayzOdyDZIsb2oBoW6O9fdHF+Ia6uIQvpc=	\N	f	viani			viani@gmail.com	f	t	2026-04-02 12:19:11.570532+01	client	6425897554			f	
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: sahel
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: agents_agentproducer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.agents_agentproducer_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: delivery_deliverytracking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.delivery_deliverytracking_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 50, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 28, true);


--
-- Name: orders_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.orders_cart_id_seq', 1, false);


--
-- Name: orders_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.orders_cartitem_id_seq', 1, false);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 1, false);


--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.orders_orderitem_id_seq', 1, false);


--
-- Name: products_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.products_category_id_seq', 11, true);


--
-- Name: products_like_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.products_like_id_seq', 3, true);


--
-- Name: products_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.products_product_id_seq', 32, true);


--
-- Name: products_productimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.products_productimage_id_seq', 46, true);


--
-- Name: products_rating_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.products_rating_id_seq', 6, true);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.users_user_id_seq', 6, true);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sahel
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: agents_agentproducer agents_agentproducer_agent_id_producer_id_ea59f734_uniq; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.agents_agentproducer
    ADD CONSTRAINT agents_agentproducer_agent_id_producer_id_ea59f734_uniq UNIQUE (agent_id, producer_id);


--
-- Name: agents_agentproducer agents_agentproducer_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.agents_agentproducer
    ADD CONSTRAINT agents_agentproducer_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: delivery_deliverytracking delivery_deliverytracking_order_id_key; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.delivery_deliverytracking
    ADD CONSTRAINT delivery_deliverytracking_order_id_key UNIQUE (order_id);


--
-- Name: delivery_deliverytracking delivery_deliverytracking_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.delivery_deliverytracking
    ADD CONSTRAINT delivery_deliverytracking_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: orders_cart orders_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.orders_cart
    ADD CONSTRAINT orders_cart_pkey PRIMARY KEY (id);


--
-- Name: orders_cart orders_cart_user_id_key; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.orders_cart
    ADD CONSTRAINT orders_cart_user_id_key UNIQUE (user_id);


--
-- Name: orders_cartitem orders_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.orders_cartitem
    ADD CONSTRAINT orders_cartitem_pkey PRIMARY KEY (id);


--
-- Name: orders_order orders_order_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_pkey PRIMARY KEY (id);


--
-- Name: orders_orderitem orders_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_pkey PRIMARY KEY (id);


--
-- Name: products_category products_category_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_pkey PRIMARY KEY (id);


--
-- Name: products_category products_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_slug_key UNIQUE (slug);


--
-- Name: products_like products_like_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_like
    ADD CONSTRAINT products_like_pkey PRIMARY KEY (id);


--
-- Name: products_like products_like_product_id_user_id_20f0a0e2_uniq; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_like
    ADD CONSTRAINT products_like_product_id_user_id_20f0a0e2_uniq UNIQUE (product_id, user_id);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id);


--
-- Name: products_productimage products_productimage_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_productimage
    ADD CONSTRAINT products_productimage_pkey PRIMARY KEY (id);


--
-- Name: products_rating products_rating_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_rating
    ADD CONSTRAINT products_rating_pkey PRIMARY KEY (id);


--
-- Name: products_rating products_rating_product_id_user_id_b30b595c_uniq; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_rating
    ADD CONSTRAINT products_rating_product_id_user_id_b30b595c_uniq UNIQUE (product_id, user_id);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- Name: agents_agentproducer_agent_id_c356f151; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX agents_agentproducer_agent_id_c356f151 ON public.agents_agentproducer USING btree (agent_id);


--
-- Name: agents_agentproducer_producer_id_fc1973bc; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX agents_agentproducer_producer_id_fc1973bc ON public.agents_agentproducer USING btree (producer_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: orders_cartitem_cart_id_529df5fa; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX orders_cartitem_cart_id_529df5fa ON public.orders_cartitem USING btree (cart_id);


--
-- Name: orders_cartitem_product_id_55063ee7; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX orders_cartitem_product_id_55063ee7 ON public.orders_cartitem USING btree (product_id);


--
-- Name: orders_order_user_id_e9b59eb1; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX orders_order_user_id_e9b59eb1 ON public.orders_order USING btree (user_id);


--
-- Name: orders_orderitem_order_id_fe61a34d; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX orders_orderitem_order_id_fe61a34d ON public.orders_orderitem USING btree (order_id);


--
-- Name: orders_orderitem_product_id_afe4254a; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX orders_orderitem_product_id_afe4254a ON public.orders_orderitem USING btree (product_id);


--
-- Name: products_category_slug_c558efae_like; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX products_category_slug_c558efae_like ON public.products_category USING btree (slug varchar_pattern_ops);


--
-- Name: products_like_product_id_804fd333; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX products_like_product_id_804fd333 ON public.products_like USING btree (product_id);


--
-- Name: products_like_user_id_0e3c48d0; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX products_like_user_id_0e3c48d0 ON public.products_like USING btree (user_id);


--
-- Name: products_product_category_id_9b594869; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX products_product_category_id_9b594869 ON public.products_product USING btree (category_id);


--
-- Name: products_product_producer_id_be45bf24; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX products_product_producer_id_be45bf24 ON public.products_product USING btree (producer_id);


--
-- Name: products_productimage_product_id_e747596a; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX products_productimage_product_id_e747596a ON public.products_productimage USING btree (product_id);


--
-- Name: products_rating_product_id_f60bd2d8; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX products_rating_product_id_f60bd2d8 ON public.products_rating USING btree (product_id);


--
-- Name: products_rating_user_id_f9283a7e; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX products_rating_user_id_f9283a7e ON public.products_rating USING btree (user_id);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: sahel
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- Name: agents_agentproducer agents_agentproducer_agent_id_c356f151_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.agents_agentproducer
    ADD CONSTRAINT agents_agentproducer_agent_id_c356f151_fk_users_user_id FOREIGN KEY (agent_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: agents_agentproducer agents_agentproducer_producer_id_fc1973bc_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.agents_agentproducer
    ADD CONSTRAINT agents_agentproducer_producer_id_fc1973bc_fk_users_user_id FOREIGN KEY (producer_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: delivery_deliverytracking delivery_deliverytracking_order_id_34f9f4d7_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.delivery_deliverytracking
    ADD CONSTRAINT delivery_deliverytracking_order_id_34f9f4d7_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_cart orders_cart_user_id_121a069e_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.orders_cart
    ADD CONSTRAINT orders_cart_user_id_121a069e_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_cartitem orders_cartitem_cart_id_529df5fa_fk_orders_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.orders_cartitem
    ADD CONSTRAINT orders_cartitem_cart_id_529df5fa_fk_orders_cart_id FOREIGN KEY (cart_id) REFERENCES public.orders_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_cartitem orders_cartitem_product_id_55063ee7_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.orders_cartitem
    ADD CONSTRAINT orders_cartitem_product_id_55063ee7_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_user_id_e9b59eb1_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_user_id_e9b59eb1_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_order_id_fe61a34d_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_order_id_fe61a34d_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_product_id_afe4254a_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_product_id_afe4254a_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_like products_like_product_id_804fd333_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_like
    ADD CONSTRAINT products_like_product_id_804fd333_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_like products_like_user_id_0e3c48d0_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_like
    ADD CONSTRAINT products_like_user_id_0e3c48d0_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_category_id_9b594869_fk_products_category_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_category_id_9b594869_fk_products_category_id FOREIGN KEY (category_id) REFERENCES public.products_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_producer_id_be45bf24_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_producer_id_be45bf24_fk_users_user_id FOREIGN KEY (producer_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productimage products_productimag_product_id_e747596a_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_productimage
    ADD CONSTRAINT products_productimag_product_id_e747596a_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_rating products_rating_product_id_f60bd2d8_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_rating
    ADD CONSTRAINT products_rating_product_id_f60bd2d8_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_rating products_rating_user_id_f9283a7e_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.products_rating
    ADD CONSTRAINT products_rating_user_id_f9283a7e_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sahel
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict gcHlZfAlMSihVQgfHUUQA0KL9S7PLOVw5yJ1omIaNir2Z7s7upnxFVlOCD3BAFN

