# Generated by Django 4.2.10 on 2026-05-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_flash_end_product_flash_price_stockalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('taille', 'Taille'), ('couleur', 'Couleur'), ('matiere', 'Matière'), ('autre', 'Autre')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('extra_price', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['type', 'label'],
            },
        ),
    ]
