# Generated by Django 4.2.10 on 2026-06-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabrication_days',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
